apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: android-redirect
spec:
  entryPoints:
    # Ports 80 and 443
    - web
    - web-secure
  routes:
    # Redirect Android users to Apache
    - match: Host(`ejemplo.marosa.vat`) && Headers(`User-Agent`, `android`)
      kind: Rule
      services:
        - name: apache
          port: 80
    # Redirect other users to NGINX
    - match: Host(`ejemplo.marosa.vat`) && HeadersRegexp(`User-Agent`, `^(?!.*android).*`)
      kind: Rule
      services:
        - name: nginx
          port: 80
