apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
    traefik.ingress.kubernetes.io/whitelist-useragents: "Android"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        - containerPort: 80