apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: ejemplo@marosa.vat
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: my-issuer-account
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik-ingress